### ISSUE TITLE
what if add the one option to set carousel-dots position?

### ISSUE THREAD

**Issue by Rachelin** [shiye515/vue-m-carousel#1]
@shiye515 
Hi, thanks for giving such wonderful component. While today i met some special requests which i should keep the carousel-dots at right corner and with customer designed UI. Although i meet all the requests with changing the css , how about to change the carousel-dots more kindly and friendly? Because i took a lot of time to read your code and demo, and then got the finial solution.

**Comment by shiye515** [comment]
- it will make the lib larger, 
- there are too many postion/style combination. 
- you can solve your problem by a little css `.carousel-indicators { text-align: right; }`
