### ISSUE TITLE
使用v-for的时候会有问题

### ISSUE THREAD

**Issue by lczhai** [shiye515/vue-m-carousel#4]
```
<carousel-item v-for="(index,v) in imgs">
         <img :src="v"  @click="log(index)">
</carousel-item>
```

使用v-for遍历写有两个问题，
1，导致循环播放不会触发（dom加载顺序晚于js的执行了，可以加个onload的解决）
2，导致轮播的首图不正确，比如两张图的情况下，首图默认为第二张了（其实不是第二张图，是下标为0的第二张图的占位图‘addonBefore’）

这两个修一下，估计会有更多人来用，毕竟做banner的时候都不会写死，一般都用v-for遍历的。
这个组件写的挺好用的！赞一个！

**Comment by shiye515** [comment]
2.0 版本已经没有上面的问题了，迁移到vue2.0，或者fork一份自己改把
