### ISSUE TITLE
微信IOS版本 carousel-dot 显示数字。您能帮我看看吗？

### ISSUE THREAD

**Issue by chengqiang1992** [shiye515/vue-m-carousel#7]
帅哥，早上好。最近两天用到您写的组件 vue-m-carousel (https://github.com/shiye515/vue-m-carousel)，效果很好很方便。但是目前有个小问题，就是在 微信IOS版本 carousel-dot 显示数字。您能帮我看看吗？

**Comment by shiye515** [comment]
indicators 改成false 或者不写这个props，就不会有 如果只是不想要数字，直接通过css text-indent:100px 即可

**Comment by chengqiang1992** [comment]
好的。谢谢了。我之前使用的方法是获取对应文本然后设置为空。感觉你这种 css text-indent:100px 更好。谢谢了。
